# Generated by Django 4.2.4 on 2023-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_size_username_on_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(default="2023-08-16"),
            preserve_default=False,
        ),
    ]
