# Generated by Django 4.2.4 on 2023-08-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_fix_fiel_name_category_on_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="comment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.comment",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.post"
            ),
        ),
    ]
