# Generated by Django 4.2.4 on 2023-08-16 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_make_fields_post_comment_no_mandatory_on_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="comment",
        ),
    ]
